Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2021
Var
// Seção de Declarações das variáveis 
   Nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
        Nota <- 100
        escreva ("Resultado", Nota)
Fimalgoritmo
